version: '3'

services:
  custom-api:
    container_name: custom-api
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: aqi
      SLEEP_TIME: 30

networks:
  default:
    external:
      name: kafka-network
