version: '3'

services:
  weatherconsumer:
    container_name: weatherconsumer
    image: twitterconsumer
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: weather
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
    command: ["python", "-u","python/weather_consumer.py"]
  fakerconsumer:
    container_name: fakerconsumer
    image: twitterconsumer
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: faker
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
    command: ["python", "-u","python/faker_consumer.py"]

  aqiconsumer:
    container_name: aqiconsumer
    image: twitterconsumer
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: aqi
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
    command: ["python", "-u","python/aqi_consumer.py"]

networks:
  default:
    external:
      name: kafka-network
